server:
  port: 8080
  forward-headers-strategy: framework

spring:
  application:
    name: iolani
  devtools:
    restart:
      additional-exclude: launcherDir/**
  jackson:
    date-format: yyyy-MM-dd'T'HH:mm:ss.SSSZ
    serialization:
      write_dates_as_timestamps: false
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
  web:
    resources:
      static-locations: classpath:/launcherDir/,classpath:/public/

debug: false
